dist: bionic
sudo: required
language: go
go: "1.14.x"

env:
  - CONTAINERD_VERSION=1.1.8 RUNSC_VERSION=release/20200219.0 TEST=untrusted-workload
  - CONTAINERD_VERSION=1.2.13 RUNSC_VERSION=release/20200219.0 TEST=untrusted-workload
  - CONTAINERD_VERSION=1.2.13 RUNSC_VERSION=release/20200219.0 TEST=runtime-handler
  - CONTAINERD_VERSION=1.2.13 RUNSC_VERSION=release/20200219.0 TEST=runtime-handler-shim-v2
  - CONTAINERD_VERSION=1.3.3 RUNSC_VERSION=release/20200219.0 TEST=runtime-handler
  - CONTAINERD_VERSION=1.3.3 RUNSC_VERSION=release/20200219.0 TEST=runtime-handler-shim-v2

go_import_path: github.com/google/gvisor-containerd-shim

addons:
  apt:
    packages:
      - socat
      - conntrack
      - ipset
      - libseccomp-dev

before_install:
  - uname -r

after_failure:
  - sudo journalctl -u containerd
  - sudo cat /var/log/*/gvisor.log

script:
  - make test
  - ./test/e2e/${TEST}/test.sh
